import pygame
from config import *

pygame.mixer.init()
pygame.mixer.music.load('../assets/music/other_pause_theme.wav')
pygame.mixer.music.play(loops=-1)
def load_assets():
    assets = {}
    ''' Game related imgs '''
    assets['enemy_img']         = pygame.image.load('../assets/img/enemy.png').convert_alpha()
    assets['enemy_img']         = pygame.transform.scale(assets['enemy_img'], (enemy_width, enemy_height))
    assets['enemy_left_img_0']  = pygame.image.load('../assets/img/enemy_left_0.png').convert_alpha()
    assets['enemy_left_img_0']  = pygame.transform.scale(assets['enemy_left_img_0'], (enemy_width, enemy_height))
    assets['enemy_left_img_1']  = pygame.image.load('../assets/img/enemy_left_1.png').convert_alpha()
    assets['enemy_left_img_1']  = pygame.transform.scale(assets['enemy_left_img_1'], (enemy_width, enemy_height))
    assets['enemy_right_img_0'] = pygame.image.load('../assets/img/enemy_right_0.png').convert_alpha()
    assets['enemy_right_img_0'] = pygame.transform.scale(assets['enemy_right_img_0'], (enemy_width, enemy_height))
    assets['enemy_right_img_1'] = pygame.image.load('../assets/img/enemy_right_1.png').convert_alpha()
    assets['enemy_right_img_1'] = pygame.transform.scale(assets['enemy_right_img_1'], (enemy_width, enemy_height))

    assets['hero_left_img']     = pygame.image.load('../assets/img/hero_left.png').convert_alpha()
    assets['hero_left_img']     = pygame.transform.scale(assets['hero_left_img'], (hero_width, hero_height))
    assets['hero_right_img']    = pygame.image.load('../assets/img/hero_right.png').convert_alpha()
    assets['hero_right_img']    = pygame.transform.scale(assets['hero_right_img'], (hero_width, hero_height))

    assets['bullet_left_img']   = pygame.image.load('../assets/img/bullet_left.png').convert_alpha()
    assets['bullet_left_img']   = pygame.transform.scale(assets['bullet_left_img'], (hero_height//3, hero_width//3))
    assets['bullet_right_img']  = pygame.image.load('../assets/img/bullet_right.png').convert_alpha()
    assets['bullet_right_img']  = pygame.transform.scale(assets['bullet_right_img'], (hero_height//3, hero_width//3))

    ''' Other imgs '''
    assets['background_day']    = pygame.image.load('../assets/img/background_day.png').convert()
    assets['background_day']    = pygame.transform.scale(assets['background_day'], (window_width, window_height))
    assets['background_day_1']  = pygame.image.load('../assets/img/background_day_1.png').convert()
    assets['background_day_1']  = pygame.transform.scale(assets['background_day_1'], (7*window_width, window_height))
    assets['background_night']  = pygame.image.load('../assets/img/background_night.png').convert()
    assets['background_night']  = pygame.transform.scale(assets['background_night'], (window_width, window_height))
    assets['play_img_0']        = pygame.image.load('../assets/img/play_0.png').convert_alpha()
    assets['play_img_0']        = pygame.transform.scale(assets['play_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['play_img_1']        = pygame.image.load('../assets/img/play_1.png').convert_alpha()
    assets['play_img_1']        = pygame.transform.scale(assets['play_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['options_img_0']     = pygame.image.load('../assets/img/options_0.png').convert_alpha()
    assets['options_img_0']     = pygame.transform.scale(assets['options_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['options_img_1']     = pygame.image.load('../assets/img/options_1.png').convert_alpha()
    assets['options_img_1']     = pygame.transform.scale(assets['options_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['quit_img_0']        = pygame.image.load('../assets/img/quit_0.png').convert_alpha()
    assets['quit_img_0']        = pygame.transform.scale(assets['quit_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['quit_img_1']        = pygame.image.load('../assets/img/quit_1.png').convert_alpha()
    assets['quit_img_1']        = pygame.transform.scale(assets['quit_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['languages_img_0']   = pygame.image.load('../assets/img/language_0.png').convert_alpha()
    assets['languages_img_0']   = pygame.transform.scale(assets['languages_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['languages_img_1']   = pygame.image.load('../assets/img/language_1.png').convert_alpha()
    assets['languages_img_1']   = pygame.transform.scale(assets['languages_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['resume_img_0']      = pygame.image.load('../assets/img/resume_0.png').convert_alpha()
    assets['resume_img_0']      = pygame.transform.scale(assets['resume_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['resume_img_1']      = pygame.image.load('../assets/img/resume_1.png').convert_alpha()
    assets['resume_img_1']      = pygame.transform.scale(assets['resume_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['yes_img_0']         = pygame.image.load('../assets/img/yes_0.png').convert_alpha()
    assets['yes_img_0']         = pygame.transform.scale(assets['yes_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['yes_img_1']         = pygame.image.load('../assets/img/yes_1.png').convert_alpha()
    assets['yes_img_1']         = pygame.transform.scale(assets['yes_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['no_img_0']          = pygame.image.load('../assets/img/no_0.png').convert_alpha()
    assets['no_img_0']          = pygame.transform.scale(assets['no_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['no_img_1']          = pygame.image.load('../assets/img/no_1.png').convert_alpha()
    assets['no_img_1']          = pygame.transform.scale(assets['no_img_1'], (main_menu_btn_w, main_menu_btn_h))
    assets['x_img_0']           = pygame.image.load('../assets/img/x_0.png').convert_alpha()
    assets['x_img_0']           = pygame.transform.scale(assets['x_img_0'], (main_menu_btn_h, main_menu_btn_h))
    assets['x_img_1']           = pygame.image.load('../assets/img/x_1.png').convert_alpha()
    assets['x_img_1']           = pygame.transform.scale(assets['x_img_1'], (main_menu_btn_h, main_menu_btn_h))
    assets['muted_img_0']       = pygame.image.load('../assets/img/muted_0.png').convert_alpha()
    assets['muted_img_0']       = pygame.transform.scale(assets['muted_img_0'] , (main_menu_btn_h, main_menu_btn_h))
    assets['muted_img_1']       = pygame.image.load('../assets/img/muted_1.png').convert_alpha()
    assets['muted_img_1']       = pygame.transform.scale(assets['muted_img_1'] , (main_menu_btn_h, main_menu_btn_h))
    assets['unmuted_img_0']     = pygame.image.load('../assets/img/unmuted_0.png').convert_alpha()
    assets['unmuted_img_0']     = pygame.transform.scale(assets['unmuted_img_0'] , (main_menu_btn_h, main_menu_btn_h))
    assets['unmuted_img_1']     = pygame.image.load('../assets/img/unmuted_1.png').convert_alpha()
    assets['unmuted_img_1']     = pygame.transform.scale(assets['unmuted_img_1'] , (main_menu_btn_h, main_menu_btn_h))
    assets['select_size_img_0'] = pygame.image.load('../assets/img/size_0.png').convert_alpha()
    assets['select_size_img_0'] = pygame.transform.scale(assets['select_size_img_0'], (main_menu_btn_w, main_menu_btn_h))
    assets['select_size_img_1'] = pygame.image.load('../assets/img/size_1.png').convert_alpha()
    assets['select_size_img_1'] = pygame.transform.scale(assets['select_size_img_1'], (main_menu_btn_w, main_menu_btn_h))
##    assets['save_img_0']        = pygame.image.load('../assets/img/save_btn_img_0.png').convert_alpha()
##    assets['save_img_0']        = pygame.transform.scale(assets['save_img_0'], (main_menu_btn_w, main_menu_btn_h))
##    assets['save_img_1']        = pygame.image.load('../assets/img/save_btn_img_1.png').convert_alpha()
##    assets['save_img_1']        = pygame.transform.scale(assets['save_img_1'], (main_menu_btn_w, main_menu_btn_h))
    explosion_anim = []
    for i in range(9):
        filename = '../assets/img/regularExplosion0{}.png'.format(i)
        img = pygame.image.load(filename).convert_alpha()
        img = pygame.transform.scale(img, (32, 32))
        explosion_anim.append(img)
    assets['explosion_anim'] = explosion_anim

    assets['score_font']     = pygame.font.Font('../assets/font/PressStart2P.ttf', 28)

    ''' Sfx '''
    assets['boom_sound']     = pygame.mixer.Sound('../assets/sfx/expl3.wav')
    assets['destroy_sound']  = pygame.mixer.Sound('../assets/sfx/expl6.wav')
    assets['pew_sound']      = pygame.mixer.Sound('../assets/sfx/pew.wav')
    
    return assets